spring:
  application:
    name: donut
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/donut
    username: donut
    password: donut
  data:
    mongodb:
      uri: mongodb+srv://junowol6:yzdDF61dZjtdoazP@donut.7868q.mongodb.net/vectorDB?retryWrites=true&w=majority&appName=Cluster0
  ai:
    vectorstore:
      mongodb:
        collection-name: documents
        initialize-schema: false
        path-name: embedding
        indexName: vector_index
        weight:
          vectorscore: 1.0
          textscore: 0.5
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small



server:
  port: 8080

logging:
  level:
    org.springframework: INFO
